{% set name = "geventhttpclient" %}
{% set version = "2.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1749f75810435a001fc6d4d7526c92cf02b39b30ab6217a886102f941c874222

  patches:
    - 0001-link-system-llhttp.patch
    - 0002-llhttp-new-ver-signature-fix.patch

build:
  number: 0
  skip: true  # [py<39]
  script: |
    # Unverndoring llhttp from sdist
    rm -rf llhttp || true
    {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - libllhttp
  run:
    - python
    - libllhttp
    - gevent
    - certifi
    - brotli-python
    - urllib3

# sdist have not all tests files to complete testing,
# so that test files used tests.common imports have been removed
# No module named 'test'
# No module named 'httplib2'
{% set SKIP_TEST_FILES = [
    "tests/test_client.py",
    "tests/test_httplib.py",
    "tests/test_httplib2.py",
    "tests/test_network_failures.py",
    "tests/test_requests.py",
    "tests/test_ssl.py",
    "tests/test_useragent.py",
] %}

{% set SKIP_TEST_OSX = [
    "test_read_multiple_header",
    "test_cookielib_compatibility",
    "test_compatibility_with_previous_api_read",
    "test_keep_alive_http_10_without_header",
    "test_keep_alive_bodyless_response_with_body",
    "test_keep_alive_bodyless_10x_request_with_body",
    "test_close_connection_and_no_content_length",
    "test_parse_error",
    "test_incomplete_response",
    "test_parse_small_blocks",
    "test_close_connection_with_content_length",
] %}

{% set SKIP_TEST_LINUX = [
] %}

{% set SKIP_TEST_WIN = [
] %}

{% set SKIP_TEST_LIST = [
] %}

{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_OSX %}  # [osx]
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_LINUX %}  # [linux]
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_WIN %}  # [win]


test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - brotli-python
  imports:
    - geventhttpclient
    - geventhttpclient._parser
    - geventhttpclient.api
    - geventhttpclient.client
    - geventhttpclient.connectionpool
    - geventhttpclient.header
    - geventhttpclient.httplib
    - geventhttpclient.requests
    - geventhttpclient.response
    - geventhttpclient.url
    - geventhttpclient.useragent
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv tests {% for file in SKIP_TEST_FILES %} --ignore={{ file }}{% endfor %} -k "not ({{ SKIP_TEST_LIST | join(' or ') }})"

about:
  home: https://github.com/geventhttpclient/geventhttpclient
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent

  # The remaining entries in this section are optional, but recommended.
  description: |
    gevent.httplib support was removed in gevent 1.0, geventhttpclient now provides
    that missing functionality.

    geventhttpclient use a fast http parser, written in C, originating from nginx,
    extracted and modified by Joyent.

    geventhttpclient has been specifically designed for high concurrency, streaming
    and support HTTP 1.1 persistent connections. More generally it is designed for
    efficiently pulling from REST APIs and streaming APIs like Twitter's.

    Safe SSL support is provided by default. geventhttpclient depends on the certifi
    CA Bundle. This is the same CA Bundle which ships with the Requests codebase, and
    is derived from Mozilla Firefox's canonical set.

    Python 2.7 and 3.4+ are supported. Python 2.6 is no longer supported.

    Use of SSL/TLS with python 2.7.9 is not recommended and may be broken.
  dev_url: https://github.com/geventhttpclient/geventhttpclient
  doc_url: https://github.com/geventhttpclient/geventhttpclient/blob/master/README.md

extra:
  recipe-maintainers:
    - bollwyvl
