{% set name = "geventhttpclient" %}
{% set version = "2.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geventhttpclient-{{ version }}.tar.gz
  sha256: 1749f75810435a001fc6d4d7526c92cf02b39b30ab6217a886102f941c874222

build:
  number: 0
  skip: true  # [py<39 or py>=313]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  # ignore_run_exports:
  #   - libcxx  # [osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - gevent
    - certifi
    - brotli
    - urllib3

# test:
#   requires:
#     - pip
#     - pytest
#     - brotli
#   imports:
#     - geventhttpclient
#   commands:
#     - pip check

about:
  home: https://github.com/geventhttpclient/geventhttpclient
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent

  # The remaining entries in this section are optional, but recommended.
  description: |
    gevent.httplib support was removed in gevent 1.0, geventhttpclient now provides
    that missing functionality.

    geventhttpclient use a fast http parser, written in C, originating from nginx,
    extracted and modified by Joyent.

    geventhttpclient has been specifically designed for high concurrency, streaming
    and support HTTP 1.1 persistent connections. More generally it is designed for
    efficiently pulling from REST APIs and streaming APIs like Twitter's.

    Safe SSL support is provided by default. geventhttpclient depends on the certifi
    CA Bundle. This is the same CA Bundle which ships with the Requests codebase, and
    is derived from Mozilla Firefox's canonical set.

    Python 2.7 and 3.4+ are supported. Python 2.6 is no longer supported.

    Use of SSL/TLS with python 2.7.9 is not recommended and may be broken.
  dev_url: https://github.com/geventhttpclient/geventhttpclient
  doc_url: https://github.com/geventhttpclient/geventhttpclient/blob/master/README.md

extra:
  recipe-maintainers:
    - bollwyvl
